# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "D:\\work\\EShopMicroservices\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basket.api:dev"
    ports:
    - "127.0.0.1:57014:57100"
    - "127.0.0.1:57214:57300"
    volumes:
    - "C:\\Users\\younis\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\work\\EShopMicroservices\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "D:\\work\\EShopMicroservices\\src:/src:rw"
    - "C:\\Users\\younis\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\younis\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_7_16_20_21_33:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "D:\\work\\EShopMicroservices\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57015:57100"
    - "127.0.0.1:57215:57300"
    volumes:
    - "C:\\Users\\younis\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\work\\EShopMicroservices\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "D:\\work\\EShopMicroservices\\src:/src:rw"
    - "C:\\Users\\younis\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\younis\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_7_16_20_21_33:/var/opt/rider-debugger:rw"
    working_dir: "/app"
